branches:
    only:
      - master
  
  jobs:
    include:
      - stage: release
        node_js: lts/*
        deploy:
          provider: script
          skip_cleanup: true
          script:
            - docker build -t torpus/learning-pug .
            - npx semantic-release
