branches:
  only:
    - master

jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - travis_retry npm install
      script:
        - docker build -t torpus/learning-pug .
        - npx semantic-release